.coveragerc
.gitignore
aa_forum/models.py
aa_forum/tests/test_models.py
aa_forum/tests/utils.py
codecov.yml
runtests.py
testauth/__init__.py
testauth/celery.py
testauth/settings.py
testauth/urls.py
testauth/wsgi.py
tox.ini

- Fixed: Last message for topic and board not updated correctly when last message is deleted
- Fixed: Last message for board not updated correctly when topic containing last message is deleted
- Added: Tests proving both fixes work
- Added: Tox to run tests

Fix last message on delete bug

---

aa_forum/models.py
aa_forum/templates/aa_forum/partials/forum/board/board-index.html
aa_forum/templates/aa_forum/partials/forum/board/new-topic-button.html
aa_forum/templates/aa_forum/partials/forum/topic/message.html
aa_forum/templates/aa_forum/partials/forum/topic/reply.html
aa_forum/templates/aa_forum/partials/menu.html
aa_forum/templates/aa_forum/partials/search/search-form.html
aa_forum/templates/aa_forum/view/forum/new-topic.html
aa_forum/templates/aa_forum/view/search/results.html
aa_forum/tests/test_integration.py
aa_forum/tests/utils.py
aa_forum/views/forum.py
tox.ini

- Adds first integrations tests for forum UI
- Fix: show "Last modified" only when message was updated
- Fix: sort message by creation timestamp, not updated timestamp, so updated messages stay in position

Add integration tests & fixes

---

.gitignore
Makefile
aa_forum/app_settings.py
aa_forum/managers.py
aa_forum/models.py
aa_forum/templates/aa_forum/partials/breadcrumb.html
aa_forum/templates/aa_forum/partials/form/required-field-hint.html
aa_forum/templates/aa_forum/partials/forum/board/board.html
aa_forum/templates/aa_forum/partials/forum/board/pagination.html
aa_forum/templates/aa_forum/partials/forum/topic/message.html
aa_forum/templates/aa_forum/partials/forum/topic/modify-message.html
aa_forum/templates/aa_forum/partials/forum/topic/pagination.html
aa_forum/templates/aa_forum/view/forum/new-topic.html
aa_forum/templates/aa_forum/view/forum/topic.html
aa_forum/tests/test_integration.py
aa_forum/tests/test_managers.py
aa_forum/tests/test_models.py
aa_forum/tests/test_views.py
aa_forum/tests/utils.py
aa_forum/views/forum.py
testauth/settings.py

- Enabled indicator showing when boards have new messages
- Add paginator on top of topics page
- Increase test coverage
- Refactor some views to reduce code duplication

Show boards with unread topics and add more tests

---

aa_forum/tests/test_views.py
aa_forum/views/forum.py

Fix: Topic unread again when opening previous pages

---

.github/workflows/tests.yml

Adds a new action that runs the test suite via tox for every push

Add github action for test suite

---

.github/workflows/tests.yml
aa_forum/templates/aa_forum/partials/administration/board-loop.html
aa_forum/templates/aa_forum/partials/administration/category-loop.html
aa_forum/templates/aa_forum/partials/search/search-form.html
aa_forum/tests/test_integration.py
aa_forum/tests/test_views_admin.py
aa_forum/views/admin.py

- Adds test for admin and search views
- Gets us to 91% test coverage with all views covered

Improve test suite

---

CHANGELOG.md
README.md
aa_forum/__init__.py

pushing v0.1.0-beta.1

---

CHANGELOG.md
README.md
aa_forum/__init__.py
setup.py
testauth/settings.py

- Configuration instructions in README.md to make it easier to understand if you
have multiple apps that use CKEditor, like `aa-bulletin-board`, and how to combine
these configurations

Release v0.1.0-beta.12

---

CHANGELOG.md
Makefile
aa_forum/__init__.py
setup.py

setup key fixed

---

CHANGELOG.md
aa_forum/__init__.py
aa_forum/templates/aa_forum/partials/forum/topic/message.html
aa_forum/templates/aa_forum/view/forum/topic.html

- "Copy message link to clipboard" button to messages in topic view
- Image lightbox, it breaks images that have a hyperlink

v0.1.0-beta.17

---

.pre-commit-config.yaml
CHANGELOG.md
aa_forum/__init__.py

Stable release v1.0.0

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
CHANGELOG.md
aa_forum/__init__.py
aa_forum/urls.py
aa_forum/views/forum.py

- Default sort order for new categories and boards moved to a constant
- Marked `forum_board_new_topic` as internal URL to prevent conflicts with a possible topic called "New Topic"
- Error 500 when trying to create a new topic with the same name of a topic that already exists in this board

Release v1.0.1

---

.pre-commit-config.yaml
aa_forum/tests/test_views_forum.py

A couple tests for exceptions and redirects added

some more tests

---

CONTRIBUTING.md
Makefile
aa_forum/tests/test_views_forum.py

- Tests for object does not exist in new topic view
- Tests for modify topic view

more tests added

---

aa_forum/scripts/fake_messages.py
aa_forum/tests/test_views_forum.py
aa_forum/tests/utils.py

Fixing some logical issues with our tests. For example, that follow-up messages cannot be before the message they follow  in their creation time.

Test logic fixes

---

.pre-commit-config.yaml
CHANGELOG.md
aa_forum/__init__.py
setup.py

- Minimum version for `allianceauth-app-utils` set to 1.8.1

Minimum version for `allianceauth-app-utils` set to 1.8.1

---

.github/workflows/automated-checks.yml
tox.ini

- Tests split into 2 groups
- Alliance Auth <= 2.8.8
- Alliance Auth >= 2.9.0
- Test for Python 3.10 added

Python 3.10 testing

---

CHANGELOG.md
aa_forum/__init__.py
aa_forum/apps.py
aa_forum/models.py
aa_forum/signals.py
aa_forum/templates/aa_forum/partials/administration/board-loop.html
aa_forum/tests/test_signals.py

- Model signals moved to their own file
- Discord webhook configuration for child boards

Release v1.2.1

---

.github/workflows/automated-checks.yml
tox.ini

Tox tests updated to match Alliance Auth (Tests for Python 3.11 added, which still is allowed to fail, since Python 3.11 is still in alpha state)

Update tox tests

---

aa_forum/helpers.py
aa_forum/tests/test_integration.py
aa_forum/views/forum.py

Helper function `send_message_to_discord_webhook` added

Helper function `send_message_to_discord_webhook` added

---

.github/workflows/automated-checks.yml
.pre-commit-config.yaml
aa_forum/templates/aa_forum/bundles/sumoselect-css.html
aa_forum/templates/aa_forum/bundles/sumoselect-js.html
aa_forum/templates/aa_forum/view/administration/index.html
setup.cfg
tox.ini

[WIP] Compatibility with AA 3.0.0

---

.github/workflows/automated-checks.yml
tox.ini

- Switching tox tests to use MySQL instead of SQLite

[MISC] Switch tox tests to mysql

---

CHANGELOG.md
aa_forum/__init__.py
aa_forum/tests/test_integration.py
aa_forum/tests/test_views_forum.py
aa_forum/urls.py
aa_forum/views/admin.py
aa_forum/views/forum.py
aa_forum/views/personal_messages.py
aa_forum/views/profile.py
aa_forum/views/search.py

- Positional arguments to URL patterns (Internal change)
- System messages and log messages improved

[RELEASE] v1.15.1

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
aa_forum/__init__.py
aa_forum/models.py
aa_forum/templates/aa_forum/partials/forum/topic/message.html
aa_forum/templatetags/aa_forum_search.py
aa_forum/tests/test_templatetags.py
testauth/settings.py
tox.ini

- Detection of the first message in the message loop in the topic and search result view
- Highlighting search terms breaks image and link tags in the search result view

[RELEASE] v1.15.2

---

aa_forum/app_settings.py
aa_forum/templates/aa_forum/ajax-render/personal-messages/message.html
aa_forum/templates/aa_forum/partials/forum/board/board.html
aa_forum/templates/aa_forum/partials/forum/board/topic.html
aa_forum/templates/aa_forum/partials/forum/topic/message.html
aa_forum/templates/aa_forum/partials/personal-messages/inbox/messages.html
aa_forum/templates/aa_forum/partials/personal-messages/reply-message/message.html
aa_forum/templates/aa_forum/partials/personal-messages/sent-messages/messages.html
aa_forum/templatetags/aa_forum_datetime.py
aa_forum/tests/test_app_settings.py
aa_forum/tests/test_templatetags.py
testauth/settings.py
tox.ini

- [Added] Support for `aa-timezones` for time zone conversions of message date/time information (#125)

[FEATURE] `aa-timezones` implementation

---

aa_forum/forms.py
aa_forum/models.py
aa_forum/tests/test_integration.py
aa_forum/tests/utils.py
aa_forum/views/forum.py
aa_forum/views/personal_messages.py
aa_forum/views/search.py

- Use models.TextChoices for forum Setting fields

[CHANGE] Use models.TextChoices for forum Setting fields

---

.github/workflows/automated-checks.yml

[MISC] Upload coverage also on push to master branch

---

.github/workflows/automated-checks.yml

[MISC] Should upload a coverage artifact as well I guess

---

.pre-commit-config.yaml
CHANGELOG.md
aa_forum/admin.py
aa_forum/app_settings.py
aa_forum/forms.py
aa_forum/helper/discord_messages.py
aa_forum/helper/user.py
aa_forum/managers.py
aa_forum/models.py
aa_forum/scripts/fake_messages.py
aa_forum/signals.py
aa_forum/templatetags/aa_forum_template_variables.py
aa_forum/templatetags/aa_forum_user.py
aa_forum/tests/test_integration.py
aa_forum/views/admin.py
aa_forum/views/forum.py
aa_forum/views/personal_messages.py
aa_forum/views/profile.py

[FIX] Pylint issues

---

aa_forum/templates/aa_forum/partials/forum/board/board.html

- Pluralisation in a template string

[FIX] Pluralisation

---

aa_forum/models.py
aa_forum/tests/test_models.py
aa_forum/views/forum.py

This will enable other apps to create a new topic in a given board.
For example:
- AA-SRP in an upcoming release for the fleet AAR
Fixes #168

[CHANGE] Enable 3rd party apps to create topics

---

CHANGELOG.md
aa_forum/forms.py
aa_forum/templates/aa_forum/partials/forum/topic/reply.html
aa_forum/tests/test_integration.py
aa_forum/views/forum.py

- Checkbox to close/re-open a topic with a reply (For OP and forum admins)

[ADD] Checkbox to close/re-open topic on reply

---

CHANGELOG.md
Makefile
aa_forum/models.py

- `Board.user_can_start_topic()` simplified to not have a variable with the same name
as the method

[CHANGE] `Board.user_can_start_topic()` simplified

---

CHANGELOG.md
aa_forum/templates/aa_forum/bundles/aa-forum-admin-js.html
aa_forum/templates/aa_forum/bundles/aa-forum-bootstrap-js.html
aa_forum/templates/aa_forum/bundles/aa-forum-ckeditor-js.html
aa_forum/templates/aa_forum/bundles/aa-forum-css.html
aa_forum/templates/aa_forum/bundles/aa-forum-oembed-js.html
aa_forum/templates/aa_forum/bundles/aa-forum-personal-messages-js.html
aa_forum/templates/aa_forum/bundles/ckeditor-js.html
aa_forum/templates/aa_forum/bundles/ckeditor5-css.html
aa_forum/templates/aa_forum/bundles/select2-css.html
aa_forum/templates/aa_forum/bundles/select2-js.html
aa_forum/templates/aa_forum/bundles/sumoselect-css.html
aa_forum/templates/aa_forum/bundles/sumoselect-js.html

- Integrity hashes to our JS and CSS files to prevent tampering

Integrity Hashes

---

aa_forum/constants.py

- Simplified the file operation

[FIX] Simplify file operation

---

aa_forum/tests/test_app_settings.py
testauth/settings/local.py

[FIX] Tests for new `allianceauth-discordbot` release

---

.github/workflows/automated-checks.yml
.pre-commit-config.yaml
CHANGELOG.md
aa_forum/tests/utils.py
aa_forum/views/forum.py
pyproject.toml
tox.ini

- Support for Python 3.8 and Python 3.9

[REMOVE] Support for Python 3.8 and Python 3.9

---

.github/workflows/automated-checks.yml
testauth/celery.py

- Update GH workflow and test framework config

[CHANGE] Update GH workflow and test framework config

---

CHANGELOG.md
aa_forum/templates/aa_forum/view/widgets/dashboard-widgets.html

- Dashboard widget Bootstrap classes (Waiting for https://gitlab.com/allianceauth/allianceauth/-/merge_requests/1631 to be merged and released)

[FIX] Dashboard widget Bootstrap classes

---

CHANGELOG.md
aa_forum/forms.py
aa_forum/locale/cs_CZ/LC_MESSAGES/django.po
aa_forum/locale/de/LC_MESSAGES/django.po
aa_forum/locale/django.pot
aa_forum/locale/es/LC_MESSAGES/django.po
aa_forum/locale/fr_FR/LC_MESSAGES/django.po
aa_forum/locale/it_IT/LC_MESSAGES/django.po
aa_forum/locale/ja/LC_MESSAGES/django.po
aa_forum/locale/ko_KR/LC_MESSAGES/django.po
aa_forum/locale/nl_NL/LC_MESSAGES/django.po
aa_forum/locale/pl_PL/LC_MESSAGES/django.po
aa_forum/locale/ru/LC_MESSAGES/django.po
aa_forum/locale/sk/LC_MESSAGES/django.po
aa_forum/locale/uk/LC_MESSAGES/django.po
aa_forum/locale/zh_Hans/LC_MESSAGES/django.po

- Improve internal forms handling

[CHANGE] Improve forms code

---

aa_forum/forms.py
aa_forum/locale/cs_CZ/LC_MESSAGES/django.po
aa_forum/locale/de/LC_MESSAGES/django.po
aa_forum/locale/django.pot
aa_forum/locale/es/LC_MESSAGES/django.po
aa_forum/locale/fr_FR/LC_MESSAGES/django.po
aa_forum/locale/it_IT/LC_MESSAGES/django.po
aa_forum/locale/ja/LC_MESSAGES/django.po
aa_forum/locale/ko_KR/LC_MESSAGES/django.po
aa_forum/locale/nl_NL/LC_MESSAGES/django.po
aa_forum/locale/pl_PL/LC_MESSAGES/django.po
aa_forum/locale/ru/LC_MESSAGES/django.po
aa_forum/locale/sk/LC_MESSAGES/django.po
aa_forum/locale/uk/LC_MESSAGES/django.po
aa_forum/locale/zh_Hans/LC_MESSAGES/django.po

[FIX] Translations

---

CHANGELOG.md
README.md
aa_forum/app_settings.py
aa_forum/helper/discord_messages.py

- Optional settings for Discord Proxy

[ADD] Optional settings for Discord Proxy

---

.github/workflows/automated-checks.yml
CHANGELOG.md
tox.ini

[ADD] Testing for Python 3.13

---

CHANGELOG.md
aa_forum/templates/aa_forum/base.html

- Missing `li` tags
Fixes # (issue)

[FIX] Missing `li` tags

---

CHANGELOG.md
aa_forum/templates/aa_forum/partials/forum/board/board.html
aa_forum/templates/aa_forum/partials/forum/board/topic.html
aa_forum/templates/aa_forum/partials/personal-messages/inbox/messages.html

- New message badges in the forum view

[FIX] New message badges in forum view

---

CHANGELOG.md
aa_forum/constants.py

- Set user agent according to MDN guidelines

[CHANGE] Set user agent according to MDN guidelines

---

CHANGELOG.md
aa_forum/constants.py

[CHANGE] Some constants reworked

---

CHANGELOG.md
aa_forum/helper/discord_messages.py
aa_forum/tests/test_dhooks_lite.py

- Proper user agent for `dhooks-lite`

[ADD] Proper user agent for `dhooks-lite`

---

CHANGELOG.md
aa_forum/forms.py
aa_forum/helper/forms.py
aa_forum/locale/django.pot

- Check for empty messages improved

[CHANGE] Check for empty messages improved

---

CHANGELOG.md
aa_forum/app_settings.py
aa_forum/templatetags/aa_forum.py

- Debug check moved to function

[CHANGE] Debug check moved to function

---

CHANGELOG.md
aa_forum/constants.py
aa_forum/helper/discord_messages.py
aa_forum/helper/static_files.py
aa_forum/templatetags/aa_forum.py
aa_forum/tests/test_app_settings.py
aa_forum/tests/test_dhooks_lite.py
aa_forum/tests/test_templatetags.py

[CHANGE] Templatetag code improved

---

CHANGELOG.md
aa_forum/apps.py

- Backend App renamed (AA Forum > Forum)

[CHANGE] Django Backend App (AA Forum > Forum)

---

.make/conf.d/development.mk
.make/conf.d/django.mk
.make/conf.d/tests.mk
Makefile

[MISC] Makefile updated

---

CHANGELOG.md
aa_forum/templates/aa_forum/base.html
aa_forum/templates/aa_forum/bundles/svg/aa-forum-icons.svg
aa_forum/templates/aa_forum/partials/forum/board/board.html
aa_forum/templates/aa_forum/partials/forum/board/topic.html
aa_forum/templates/aa_forum/view/forum/index.html
aa_forum/templates/aa_forum/view/widgets/dashboard-widgets.html

[CHANGE] SVG sprite optimizations

---

.coveragerc
.github/workflows/automated-checks.yml
.github/workflows/release.yml
.make/conf.d/development.mk
.make/conf.d/django-esi.mk
.make/conf.d/django.mk
.make/conf.d/git.mk
.make/conf.d/pre-commit.mk
.make/conf.d/redis.mk
.make/conf.d/tests.mk
.pre-commit-config.yaml
Makefile
package-lock.json
package.json

- General project files updates

[MISC] General project updates

---

CHANGELOG.md
aa_forum/__init__.py

- Switch to Terser for JavaScript compression
- Translations updated

[RELEASE] v2.13.1
